# Generated by Django 6.0.4 on 2026-04-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Страна происхождения',
                'verbose_name_plural': 'Страны происхождения',
            },
        ),
        migrations.CreateModel(
            name='CoffeeSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('processing', models.CharField(blank=True, max_length=100, verbose_name='Обработка')),
                ('tasting_notes', models.TextField(verbose_name='Вкусовые ноты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (опционально)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.coffeeorigin', verbose_name='Происхождение')),
            ],
            options={
                'verbose_name': 'Сорт кофе',
                'verbose_name_plural': 'Сорта кофе',
            },
        ),
    ]
