# Generated by Django 6.0.4 on 2026-06-18 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeesort',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_coffees', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у пользователей'),
        ),
    ]
